# Use Node 18 Alpine
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Set environment variable for memory limit
ENV NODE_OPTIONS=--max_old_space_size=4096

# Copy package files
COPY package.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy app source files
COPY tsconfig.json ./
# COPY nodemon.json ./ # Optional, can skip if not needed in prod
COPY src ./src
COPY database ./database

# Add entrypoint if needed
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

# Start the app
CMD ["npm", "start"]
