name: Docker Build and Push

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t pomegranatei/frontend:latest -f frontend/Dockerfile.dev ./frontend
          docker push pomegranatei/frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t pomegranatei/backend:latest -f backend/Dockerfile.dev ./backend
          docker push pomegranatei/backend:latest

      # Optional: If not using Render’s DB
      - name: Build and Push DB
        run: |
          docker build -t pomegranatei/database:latest -f docker/database/Dockerfile .
          docker push pomegranatei/database:latest
